version: "3"

env:
  APP_DB_URL: postgresql://bank:welcome@localhost:5432/bank?sslmode=disable

dotenv:
  - .env

tasks:
  container-up:
    cmds:
      - docker-compose up -d
  container-down:
    cmds:
      - docker-compose down --remove-orphans --volumes
  migrate-up:
    cmds:
      - migrate -path db/migrations -database $APP_DB_URL -verbose up
  migrate-down:
    cmds:
      - migrate -path db/migrations -database $APP_DB_URL -verbose down -all
  sqlc-generate:
    cmds:
      - sqlc generate
